@startuml

abstract class Hardware {
  - warehouseId : Long
  - manufacturer : String
  - model : String
}

class Server extends Hardware {
  - processor : String
  - memory : String
  - pciBuses : int
  - pcixBuses : int
  - pcieBuses : int
}

class Laptop extends Hardware {
  - processor : String
  - memory : String
  - diskPorts : int
}

@startuml

abstract class Hardware {
  - warehouseId : long
  - manufacturer : String
  - model : String
}

class Laptop extends Hardware
class Server extends Hardware
class Disk extends Hardware
class StorageController extends Hardware

interface HardwareRepository
class CsvHardwareRepository

CsvHardwareRepository --> Laptop
CsvHardwareRepository --> Server
CsvHardwareRepository --> Disk
CsvHardwareRepository --> StorageController
CsvHardwareRepository ..|> HardwareRepository

class Setup {
  - id: long
  - type: SetupType
  - laptop: Laptop
  - server: Server
  - disks: List<Disk>
  - controllers: List<StorageControllerWithDisks>
}

class SetupService
class SetupRepository

Setup --> Laptop
Setup --> Server
Setup --> Disk
Setup --> StorageControllerWithDisks
SetupService --> SetupRepository
SetupService --> HardwareRepository

@enduml
